services:
  n8n:
    container_name: n8n
    stdin_open: true
    tty: true
    ports:
        - 5678:5678
    volumes:
        - /mnt/portainer-compose-unpacker/stacks/n8n/n8n/.n8n:/home/node/.n8n
    image: docker.n8n.io/n8nio/n8n
    environment:
        - GENERIC_TIMEZONE=America/Santiago
        - TZ=America/Santiago
    restart: unless-stopped
